### PR TITLE
feat: support LibreHardwareMonitor

### PR DESCRIPTION
**Pull request by abichinger**
fix: #4

### CODE REVIEW

**Comment by abichinger** [comment]
@mnaiman pls review

**Comment by mnaiman** [comment]
Can you please drop me here x64 build?
Im not at my development PC now.
About Dispose, I strongly suggest to use "using" keyword instead calling Dispose function. It internally generate try/finally statement to Dispose even in case of exception.

**Comment by abichinger** [comment]
[x64.zip](https://github.com/abichinger/Rainmeter-HardwareMonitor/files/7645587/x64.zip)

**Comment by mnaiman** [comment]
One small adjustment.
Project should target at lest 4.5.1
<TargetFrameworkVersion>v4.5.1</TargetFrameworkVersion>

.Net 2.0 is not preinstalled in Windows 10/11
.Net 4.5.1 is supported on Windows 7 up - out of the box

**Comment by abichinger** [comment]
@mnaiman thanks for your contribution and all the hints.
I will release it soon.

About the framework target, I will try to raise it.

**Pull request merged**
